### ISSUE TITLE
Unable to create new Question.  

### ISSUE THREAD

**Issue by sundarsv** [sundarsv/upgrad_course5_ass1gnment#21]
The question get's created BUT looks like we are unable to populate question_category table.

Getting error, 'java.lang.IndexOutOfBoundsException: Index 2 out-of-bounds for length 2', possible at 
at org.upgrad.services.QuestionServiceImp.addQuestion(QuestionServiceImp.java:29) ~[classes/:na].

Swagger params:
categoryId: 4
content: Who played Gandhi in the movie 'Gandhi'

Response body:
{
  "timestamp": "2018-07-13T00:16:47.026+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Invalid parameter index! You seem to have declare too little query method parameters!",
  "path": "/api/question"
}

Response code: 500

**Comment by Apoorva2405** [comment]
Fixed in PR:
https://github.com/sundarsv/upgrad_course5_ass1gnment/pull/29
