### ISSUE TITLE
Check if all method names and variable names are as per Upgrad platform and test cases.

### ISSUE THREAD

**Issue by sundarsv** [sundarsv/upgrad_course5_ass1gnment#26]
Ideally, the method names we use and variable names should match what is in upgrad platform.  This will help them in running test cases.

Let's see if we can find the time to go through these.

**Comment by Apoorva2405** [comment]
This is done.All test cases fixed:
Fixed in 
https://github.com/sundarsv/upgrad_course5_ass1gnment/pull/58
Now only one test case is failing in LikeFollowService which is commented

**Comment by sundarsv** [comment]
I tried checking LikeFollowService but NOT sure why it's failing.  I checked in Swagger and DB and the changes are getting set there.  Closing this.
