### ISSUE TITLE
deleteQuestion > deleting a non existent question throw 500

### ISSUE THREAD

**Issue by sundarsv** [sundarsv/upgrad_course5_ass1gnment#36]
NOT SURE IF WE NEED TO FIX THIS AS THIS WASN'T A REQUIREMENT IN UPGRAD PLATFORM.
Trying deleting a quesiton ID that does NOT exist.

error from console: org.springframework.aop.AopInvocationException: Null return value from advice does not match primitive return type for: public abstract int org.upgrad.repositories.QuestionRepository.getUserIdByQuestion(int)

![image](https://user-images.githubusercontent.com/4122675/42721374-91b9849e-8757-11e8-9bc7-32cafad1937e.png)

**Comment by Apoorva2405** [comment]
@sundarsv I think since there is no mention of this, we wont be adding any additonal code for this as discussed on call.
Shall we close this mentioning "wont fix" label?

**Comment by sundarsv** [comment]
Not a requirement from upgrad team.  Closing this.
