### ISSUE TITLE
deleteQuestion > Admin is UNABLE to delete other's question

### ISSUE THREAD

**Issue by sundarsv** [sundarsv/upgrad_course5_ass1gnment#37]
Logged in as admin.  But unable to delete question by others.

Getting, 'You do not have rights to delete this question!' error.

**Comment by Apoorva2405** [comment]
@sundarsv I am able to delete this.Can you please retest or mention the scenario ?
Also all test cases (including admin scenario) are also passing

**Comment by sundarsv** [comment]
Ya.  works now.  closing.
