### ISSUE TITLE
createAnswer API > method should NOT be referred 'AnswerQuestion'

### ISSUE THREAD

**Issue by sundarsv** [sundarsv/upgrad_course5_ass1gnment#38]
The createAnswer API is being referred to as 'AnswerQuestion'.  This needs to change as it can cause issues with test cases.  It should be called 'createAnswer'.

NOTE:  THIS CAN CAUSE ISSUES WITH OTHER DEPENDENT APIs.

![image](https://user-images.githubusercontent.com/4122675/42721474-13d7ec6c-8759-11e8-941d-a32dba1d5827.png)

**Comment by sugandhakhera** [comment]
Fixed
