### ISSUE TITLE
Answer Controller > has extra files

### ISSUE THREAD

**Issue by sundarsv** [sundarsv/upgrad_course5_ass1gnment#39]
See screenshot.  I see AnswerController.java has further AnswerController and ValueComparator files.

NOTE:  MOVING FILES CAN HAVE OVERALL IMPACT ON PROJECT.

![image](https://user-images.githubusercontent.com/4122675/42721492-49a5e6e6-8759-11e8-9c07-6fdf04c839ee.png)

**Comment by sugandhakhera** [comment]
That is Comparator class used for comparison.
