### ISSUE TITLE
getAllAnswersToQuestion > throws blank result

### ISSUE THREAD

**Issue by sundarsv** [sundarsv/upgrad_course5_ass1gnment#40]
This should work for all users.  But it seems to throw result ONLY if the user is same use who answered it.  Upgrad specifies that we should retrieve answers to a question for all user logins.

![image](https://user-images.githubusercontent.com/4122675/42721588-ee1b57b4-875a-11e8-814a-36fe444908bb.png)

**Comment by sugandhakhera** [comment]
Fixed
