### ISSUE TITLE
GetAllanswersToQuestions expected return type is List<Answer>

### ISSUE THREAD

**Issue by Apoorva2405** [sundarsv/upgrad_course5_ass1gnment#54]
Currrently, string type is returned

**Comment by sugandhakhera** [comment]
While changing name, i am getting   "message": "Failed to convert from type [java.lang.Object[]] to type [org.upgrad.models.Answer] for value '{2, black, 2018-07-11 20:10:24.020743, 1, 693, 2018-07-11}'; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.Integer] to type [org.upgrad.models.Answer]",

**Comment by Apoorva2405** [comment]
@sugandhakhera What type are you trying to set?

**Comment by Apoorva2405** [comment]
@sugandhakhera Fixed and merged in:
https://github.com/sundarsv/upgrad_course5_ass1gnment/pull/58
