### ISSUE TITLE
Signin API failing

### ISSUE THREAD

**Issue by sundarsv** [sundarsv/upgrad_course5_ass1gnment#57]
Tried to login as 'admin' and got this error in console. org.postgresql.util.PSQLException: The column name user_name was not found in this ResultSet.

Screengrab from swagger response body:
![image](https://user-images.githubusercontent.com/4122675/42727377-28ef3924-87c3-11e8-842f-81ec04b136d5.png)

**Comment by Apoorva2405** [comment]
@Please delete old target folder and rebuild

**Comment by sundarsv** [comment]
Done.  and works.  Closing.
