### ISSUE TITLE
major issues

### ISSUE THREAD

**Issue by kan07061990** [sundarsv/upgrad_course5_ass1gnment#62]
admin controller delete user not working
two apis of answer controller getallanswerbyuser and getallanswertoquestion not working

**Comment by kan07061990** [comment]
delete is not working for users having notification

**Comment by Apoorva2405** [comment]
Fixed these two:
two apis of answer controller getallanswerbyuser and getallanswertoquestion not working
https://github.com/sundarsv/upgrad_course5_ass1gnment/pull/63

**Comment by kan07061990** [comment]
fixed delete issue
